# Generated by Django 2.2.7 on 2019-11-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perawat',
            fields=[
                ('id_perawat', models.AutoField(primary_key=True, serialize=False)),
                ('nama_perawat', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('jenis_kelamin', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'perawat',
            },
        ),
    ]
